!!****if* source/physics/sourceTerms/KromeChemistry/KromeChemistry_init
!!
!! NAME
!!  KromeChemistry_init
!!
!! DESCRIPTION
!!  Initialize runtime parameters and the network<->FLASH species map for the
!!  JAFF-generated chemistry unit. Auto-generated by jaffgen (template: flash).
!!
!!  Unlike the KROME unit this needs no krome_init(): the network is compiled
!!  directly from the generated commons/reactions/fluxes/ode modules. The species
!!  order is exactly the order jaffgen emits, so the names below line up 1:1 with
!!  the idx_* parameters in the commons module.
!!
!!***

subroutine KromeChemistry_init()

   use KromeChemistry_data
   use commons, ONLY : common_crate, common_av
   use RuntimeParameters_interface, ONLY : RuntimeParameters_get
   use PhysicalConstants_interface, ONLY: PhysicalConstants_get
   use Multispecies_interface, ONLY : Multispecies_getProperty
   use Simulation_interface, ONLY : Simulation_mapStrToInt

   implicit none

#include "constants.h"
#include "Flash.h"
#include "Multispecies.h"

   integer :: n
   character(len=16) :: network_species_names(NSPECIES)

   call RuntimeParameters_get("useKromeChemistry", useKromeChemistry)
   call RuntimeParameters_get("krome_temp_floor", krome_temp_floor)
   call RuntimeParameters_get("krome_density_threshold", krome_density_threshold)
   call RuntimeParameters_get("krome_crate", krome_crate)
   call RuntimeParameters_get("krome_av", krome_av)
   call PhysicalConstants_get("proton mass", mp)

   ! network variables consumed by the generated rate expressions
   common_crate = krome_crate
   common_av    = krome_av

   ! Species names in network (jaffgen) order. Index n here == idx_* == n.
   ! $JAFF REPEAT idx, specie_with_normalized_sign IN species_with_normalized_sign $[POS j NEG k]$
   network_species_names($idx+1$) = "$specie_with_normalized_sign$"
   ! $JAFF END

   do n = 1, NSPECIES
     call Simulation_mapStrToInt(trim(network_species_names(n)), specieMap(n), MAPBLOCK_UNK)
     call Multispecies_getProperty(specieMap(n), A, amu(n))
   enddo

   return

end subroutine KromeChemistry_init
