!!****if* source/physics/sourceTerms/KromeChemistry/KromeChemistry_data
!!
!! NAME
!!  KromeChemistry_data
!!
!! DESCRIPTION
!!  Store the data for the JAFF-generated chemistry unit.
!!  Auto-generated by jaffgen (template collection: flash).
!!
!!***

module KromeChemistry_data

  implicit none

#include "constants.h"
#include "Flash.h"

  logical, save :: useKromeChemistry
  real, save    :: mp, krome_temp_floor, krome_density_threshold
  real, save    :: krome_crate, krome_av
  integer, save, dimension(NSPECIES) :: specieMap
  real, save, dimension(NSPECIES)    :: amu

end module KromeChemistry_data
