!!****if* source/physics/sourceTerms/KromeChemistry/KromeChemistry
!!
!! NAME
!!  KromeChemistry
!!
!! SYNOPSIS
!!  call KromeChemistry(integer :: blockCount,
!!                      integer, dimension(blockCount) :: blockList,
!!                      real :: dt)
!!
!! DESCRIPTION
!!  Apply the JAFF-generated chemistry network to all cells in the given blocks.
!!  Auto-generated by jaffgen (template collection: flash).
!!
!!  The network right-hand side (fex) comes from the generated ode module; the
!!  ODE integrator is FLASH's own ODEPACK/DLSODES (opkda1/opkda2/opkdmain),
!!  shared by the KromeChemistry unit. jaffgen supplies no integrator.
!!
!!***

subroutine KromeChemistry(blockCount, blockList, dt)

  use KromeChemistry_data
  use commons, ONLY : nspecs, idx_tgas
  use ode, ONLY : fex, jes
  use Timers_interface, ONLY : Timers_start, Timers_stop
  use Grid_interface, ONLY : Grid_getBlkIndexLimits, Grid_getBlkPtr, Grid_releaseBlkPtr
  use Eos_interface, ONLY : Eos_wrapped

  implicit none

#include "constants.h"
#include "Flash.h"
#include "Eos.h"

  integer, intent(in) :: blockCount
  integer, intent(in), dimension(blockCount) :: blockList
  real, intent(in) :: dt

  integer :: i, j, k, n, blockID, thisBlock
  integer, dimension(2,MDIM) :: blkLimits, blkLimitsGC
  real, dimension(NSPECIES) :: x, xn
  real :: tmp, rho

  ! DLSODES work space. neq = species + one gas-temperature slot.
  integer, parameter :: neq = NSPECIES + 1
  integer, parameter :: lrw = 20 + 3*neq**2 + 20*neq
  integer, parameter :: liw = 30
  real    :: rwork(lrw), rtol(neq), atol(neq), nvec(neq), tloc, tend
  integer :: iwork(liw), itol, itask, istate, iopt, mf

  real, pointer, dimension(:,:,:,:) :: solnData

  if (.not. useKromeChemistry) return

  call Timers_start("chemistry")

  ! Integrator controls (see the DLSODES documentation in opkdmain.f).
  itol  = 4      ! rtol and atol are both arrays
  itask = 1      ! normal integration to tend
  iopt  = 0      ! no optional inputs
  mf    = 222    ! stiff, internally generated sparse Jacobian
  rtol  = 1.0e-6
  atol  = 1.0e-6

  do thisBlock = 1, blockCount

     blockID = blockList(thisBlock)

     call Grid_getBlkIndexLimits(blockID, blkLimits, blkLimitsGC)
     call Grid_getBlkPtr(blockID, solnData)

     do k = blkLimits(LOW,KAXIS), blkLimits(HIGH,KAXIS)
        do j = blkLimits(LOW,JAXIS), blkLimits(HIGH,JAXIS)
           do i = blkLimits(LOW,IAXIS), blkLimits(HIGH,IAXIS)

              tmp = solnData(TEMP_VAR,i,j,k)
              rho = solnData(DENS_VAR,i,j,k)

              ! skip cells below the chemistry density threshold
              if (rho .lt. krome_density_threshold) cycle

              ! mass fractions -> number densities
              do n = 1, NSPECIES
                 x(n)  = solnData(specieMap(n),i,j,k)
                 xn(n) = x(n) * rho / mp / amu(n)
              enddo

              ! assemble the DLSODES state vector: species then temperature
              nvec(1:NSPECIES) = xn(:)
              nvec(idx_tgas)   = max(tmp, krome_temp_floor)

              tloc   = 0.0
              tend   = dt
              istate = 1
              rwork  = 0.0
              iwork  = 0

              call DLSODES(fex, neq, nvec, tloc, tend, itol, rtol, atol, &
                           itask, istate, iopt, rwork, lrw, iwork, liw, jes, mf)

              ! unpack integrated state
              xn(:) = nvec(1:NSPECIES)
              tmp   = nvec(idx_tgas)

              ! number densities -> mass fractions
              do n = 1, NSPECIES
                 x(n) = xn(n) * mp * amu(n) / rho
                 solnData(specieMap(n),i,j,k) = x(n)
              enddo

              solnData(TEMP_VAR,i,j,k) = tmp

           enddo
        enddo
     enddo

     call Grid_releaseBlkPtr(blockID, solnData)

     call Eos_wrapped(MODE_DENS_TEMP, blkLimits, blockID)

  enddo

  call Timers_stop("chemistry")

  return

end subroutine KromeChemistry
