!!****if* source/Simulation/SimulationComposition/KromeChemistry/Simulation_initSpecies
!!
!! NAME
!!  Simulation_initSpecies
!!
!! DESCRIPTION
!!  Register the network species and their Multispecies properties.
!!  Auto-generated by jaffgen (template collection: flash).
!!
!!  Species names and masses are emitted by jaffgen in network order; the two
!!  REPEAT blocks fill parallel arrays indexed by the same idx, so name(n) and
!!  mass(n) refer to the same species. Masses are physical CGS grams; the A
!!  (mass-number) property is mass / proton-mass.
!!
!!  PLACEHOLDERS: Z (protons), N (neutrons) and E (electrons) are emitted as 0
!!  and GAMMA is hardcoded to the monatomic value 5/3. Fill these in per network.
!!
!!***

subroutine Simulation_initSpecies()

  use Multispecies_interface, ONLY : Multispecies_setProperty
  use Simulation_interface, ONLY : Simulation_mapStrToInt
  use PhysicalConstants_interface, ONLY: PhysicalConstants_get

  implicit none

#include "constants.h"
#include "Flash.h"

#ifdef FLASH_MULTISPECIES
#include "Multispecies.h"

  integer :: n, isotope
  real :: mp
  character(len=16) :: names(NSPECIES)
  real :: masses(NSPECIES)   ! grams (CGS)

  call PhysicalConstants_get("proton mass", mp)

  ! Species names, network (jaffgen) order.
  ! $JAFF REPEAT idx, specie_with_normalized_sign IN species_with_normalized_sign $[POS j NEG k]$
  names($idx+1$) = "$specie_with_normalized_sign$"
  ! $JAFF END

  ! Species masses in grams, same order.
  ! $JAFF REPEAT idx, specie_mass IN specie_masses
  masses($idx+1$) = $specie_mass$
  ! $JAFF END

  do n = 1, NSPECIES
    call Simulation_mapStrToInt(trim(names(n)), isotope, MAPBLOCK_UNK)
    if (isotope == NONEXISTENT) cycle
    call Multispecies_setProperty(isotope, A, masses(n)/mp)   ! mass number
    call Multispecies_setProperty(isotope, Z, 0.0)            ! PLACEHOLDER: protons
    call Multispecies_setProperty(isotope, N, 0.0)            ! PLACEHOLDER: neutrons
    call Multispecies_setProperty(isotope, E, 0.0)            ! PLACEHOLDER: electrons
    call Multispecies_setProperty(isotope, GAMMA, 5.0/3.0)    ! monatomic (hardcoded)
  enddo

#endif

  return

end subroutine Simulation_initSpecies
